name: SemanticReleaseTest

trigger:
  - master

variables:
  buildConfiguration: Release

jobs:
- job: Job1
  pool:
    vmImage: 'windows-latest'

  steps:
  - script: >
      npx -p semantic-release
      -p @semantic-release/changelog
      -p @semantic-release/git
      -p semantic-release-ado@1.3.0-alpha.1
      semantic-release --dry-run
    env: { GH_TOKEN: $(GitHubToken)}
    displayName: 'Semantic release'

  - powershell: |
      echo "##vso[task.setvariable variable=versionNumber;isOutput=true]$(version)"
    name: setOutputVar

  - script: echo $(version)
    displayName: 'Show next version'

- job: Job2
  dependsOn: Job1
  pool:
    vmImage: 'windows-latest'
  variables:
    versionNumber: $[ dependencies.Job1.outputs['setOutputVar.versionNumber'] ]
  
  steps:
  - script: echo $(versionNumber)
    displayName: 'Show next version'
