name: SemanticReleaseTest

trigger:
  - master

variables:
  buildConfiguration: Release

jobs:
- job: Job1
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - script: >
      npx -p semantic-release
      -p @semantic-release/changelog
      -p @semantic-release/git
      -p semantic-release-ado
      semantic-release
    env: { GH_TOKEN: $(GitHubToken)}
    displayName: 'Semantic release'

  - powershell: |
      echo "##vso[task.setvariable variable=versionNumber;isOutput=true]$(nextRelease)"
    name: setOutputVar

  - script: echo $(version)
    displayName: 'Show next version'

- job: Job2
  dependsOn: Job1
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    versionNumber: $[ dependencies.Pack.outputs['setOutputVars.versionNumber'] ]
  
  steps:
  - script: echo $(versionNumber)
    displayName: 'Show next version'
